apiVersion: v1
kind: Service
metadata:
  name: temporal-codec
  namespace: temporal-sandbox
spec:
  clusterIP: 172.20.176.159
  clusterIPs:
    - 172.20.176.159
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: temporal-codec
  sessionAffinity: None
  type: ClusterIP